### ISSUE TITLE
Cannot convert undefined to a BigInt

### ISSUE THREAD

**Issue by CyrusVorwald** [balancednetwork/balanced-network-interface#1299]
When I load the application with my wallets signed in, the following error is logged in the console:

TypeError: Cannot convert undefined to a BigInt
    at Function.value (6.4647a2d2.chunk.js:2:146092)
    at t.e (6.4647a2d2.chunk.js:2:111235)
    at new t (6.4647a2d2.chunk.js:2:113937)
    at t.fromRawAmount (6.4647a2d2.chunk.js:2:114129)
    at main.f0de9844.chunk.js:1:571213
    at d (6.4647a2d2.chunk.js:2:2705488)
    at Generator._invoke (6.4647a2d2.chunk.js:2:2705276)
    at Generator.next (6.4647a2d2.chunk.js:2:2705917)
    at r (6.4647a2d2.chunk.js:2:108571)
    at s (6.4647a2d2.chunk.js:2:108774)

**Comment by swiftcc624** [comment]
@CyrusVorwald I can't reproduce it on my side.

**Comment by CyrusVorwald** [comment]
I am on travel and will try to reproduce when I get back next week
